server:
  port: 8081

logging:
  level:
    com.zhoutianyu.learnspringboot: debug
    org.springframework.web: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 配置数据源类型
      url: jdbc:mysql://localhost:3306/basessm?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 3333
      # 初始化，最小，最大连接数
      initialSize: 10
      minidle: 10
      maxActive: 18
      # 获取数据库连接等待的超时时间
      maxWait: 60000
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置测试查询语句
      validationQuery: SELECT 1 FROM dual
      # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
      filters: stat
  #springboot版本可能与druid版本不兼容，使用下面的配置兼容
  main:
    allow-bean-definition-overriding: true

  flyway:
    baseline-on-migrate: true
    clean-disabled: true
    locations: classpath:/flyway/dev
    out-of-order: true



